const apiRoutes = {
	recipes: "/recipes",
	recipe: (recipeId) => `/recipes/${recipeId}`,
	recipeMetadata: (recipeId) => `/recipes/${recipeId}/metadata`,
	suggestions: "/suggestions",
	userSuggestions: "/users/me/suggestions",
	userRecipes: "/users/me/recipes",
	categories: "/categories",
	meals: "/meals",
	userWishlist: "/users/me/wishlist",
	userWishlistItem: (recipeId) => `/users/me/wishlist/${recipeId}`,
	userCollections: "/users/me/collections",
	userCollection: (collectionId) => `/users/me/collections/${collectionId}`,
	userCollectionRecipes: (collectionId) => `/users/me/collections/${collectionId}/recipes`,
	userCollectionRecipe: (collectionId, recipeId) => `/users/me/collections/${collectionId}/recipes/${recipeId}`,
	userRecipeNote: (recipeId) => `/users/me/recipes/${recipeId}/note`,
	pantry: "/users/me/pantry",
	pantryItem: (pantryId) => `/users/me/pantry/${pantryId}`,
	userRatings: "/users/me/ratings",
	userRecipeRating: (recipeId) => `/recipes/${recipeId}/rating`,
	userRecipeRatingDelete: (recipeId) => `/recipes/${recipeId}/rating`,
	recipeReviews: (recipeId) => `/recipes/${recipeId}/reviews`,
	authToken: "/auth/token",
	authLogin: "/auth/login",
	authSignup: "/auth/signup",
	authRefresh: "/auth/refresh",
	userProfile: "/users/me/profile",
	userPassword: "/users/me/password",
	mealPlans: "/users/me/meal-plans",
	mealPlan: (planId) => `/users/me/meal-plans/${planId}`,
	mealPlanItems: (planId) => `/users/me/meal-plans/${planId}/items`,
	mealPlanItem: (planId, itemId) => `/users/me/meal-plans/${planId}/items/${itemId}`,
	shoppingList: "/users/me/shopping-list",
	shoppingListItems: "/users/me/shopping-list/items",
	shoppingListItem: (itemId) => `/users/me/shopping-list/items/${itemId}`,
	shoppingListFromRecipe: "/users/me/shopping-list/from-recipe",
	shoppingListCompleted: "/users/me/shopping-list/completed",
	databaseHealth: "/health/ready",
	serverHealth: "/health/live",
};

export const getUserRecipeRatingRoute = (recipeId) =>
	apiRoutes.userRecipeRating(recipeId);

export { apiRoutes };
