import { useEffect, useMemo, useState } from "react";
import { Check } from "lucide-react";
import Input from "@/shared/ui/Input";
import { cn } from "@/shared/lib/utils";
import { useRecipesQuery } from "@/features/food/api/useRecipesQuery";
import { useAllRecipesQuery } from "@/features/recipes/api/useRecipeQueries";
import type { RecipeSummary } from "@/shared/api/contracts";
import { useSavedRecipeIdsQuery } from "../api/planningQueries";

const MIN_SEARCH_LENGTH = 2; const SEARCH_DEBOUNCE_MS = 250;
type RecipePickerProps = { selectedRecipeId: number | null; onSelect: (recipe: RecipeSummary) => void; autoFocus?: boolean };
const RecipeOption = ({ recipe, selectedRecipeId, onSelect }: { recipe: RecipeSummary; selectedRecipeId: number | null; onSelect: (recipe: RecipeSummary) => void }) => { const selected = selectedRecipeId === recipe.recipe_id; return <button type="button" className={cn("flex min-h-11 w-full items-center justify-between gap-3 rounded-xl border px-3 py-2 text-left text-sm font-semibold transition hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring", selected ? "border-primary bg-secondary text-secondary-foreground" : "border-border bg-background")} onClick={() => onSelect(recipe)} aria-pressed={selected}><span className="truncate">{recipe.recipe_name}</span>{selected && <Check className="size-4 shrink-0 text-primary" aria-hidden="true" />}</button>; };
const RecipePicker = ({ selectedRecipeId, onSelect, autoFocus = false }: RecipePickerProps) => {
	const [searchTerm, setSearchTerm] = useState(""); const [debouncedSearch, setDebouncedSearch] = useState(""); const savedRecipeIdsQuery = useSavedRecipeIdsQuery(); const allRecipesQuery = useAllRecipesQuery();
	useEffect(() => { const timer = window.setTimeout(() => setDebouncedSearch(searchTerm.trim()), SEARCH_DEBOUNCE_MS); return () => window.clearTimeout(timer); }, [searchTerm]);
	const discoveryQuery = useRecipesQuery({ q: debouncedSearch, categoryId: "", mealId: "", sort: "popular" as const, filter: "", page: 1, limit: 8 }, { enabled: debouncedSearch.length >= MIN_SEARCH_LENGTH });
	const savedRecipeIds = savedRecipeIdsQuery.data ?? []; const savedRecipes = useMemo(() => { const savedIds = new Set(savedRecipeIds); return (allRecipesQuery.data ?? []).filter((recipe) => savedIds.has(recipe.recipe_id)); }, [allRecipesQuery.data, savedRecipeIds]);
	const hint = "text-sm leading-6 text-muted-foreground";
	return <div className="grid gap-6"><section aria-labelledby="saved-recipe-picker-title"><div className="mb-3 flex items-center justify-between"><h3 id="saved-recipe-picker-title" className="font-black">Saved recipes</h3><span className="rounded-full bg-muted px-2 py-1 text-xs font-bold text-muted-foreground">{savedRecipes.length}</span></div>{savedRecipeIdsQuery.isPending || allRecipesQuery.isPending ? <p className={hint}>Loading your saved recipes…</p> : savedRecipes.length === 0 ? <p className={hint}>Save a recipe first, or search the recipe library below.</p> : <div className="grid max-h-48 gap-2 overflow-y-auto pr-1">{savedRecipes.map((recipe) => <RecipeOption key={recipe.recipe_id} recipe={recipe} selectedRecipeId={selectedRecipeId} onSelect={onSelect} />)}</div>}</section><section aria-labelledby="discover-recipe-picker-title"><h3 id="discover-recipe-picker-title" className="mb-3 font-black">Find another recipe</h3><label htmlFor="planning-recipe-search" className="mb-2 block text-sm font-bold">Search recipes</label><Input id="planning-recipe-search" name="recipeSearch" type="search" placeholder="Try chicken, pasta, soup…" value={searchTerm} onChange={(event) => setSearchTerm(event.target.value)} autoFocus={autoFocus} autoComplete="off" />{debouncedSearch.length < MIN_SEARCH_LENGTH ? <p className={hint + " mt-2"}>Type at least 2 characters to search the library.</p> : discoveryQuery.isPending ? <p className={hint + " mt-2"} role="status">Searching recipes…</p> : discoveryQuery.error ? <p className="mt-2 text-sm font-semibold text-destructive" role="alert">Recipe search is unavailable. Try again.</p> : <div className="mt-3 grid max-h-56 gap-2 overflow-y-auto pr-1" aria-label="Recipe search results">{(discoveryQuery.data?.recipes ?? []).map((recipe) => <RecipeOption key={recipe.recipe_id} recipe={recipe} selectedRecipeId={selectedRecipeId} onSelect={onSelect} />)}{discoveryQuery.data?.recipes.length === 0 && <p className={hint}>No recipes match that search.</p>}</div>}</section></div>;
};
export default RecipePicker;
